# get api_id & api_hash from my.telegram.org
api_id: '22118129'
api_hash: '43c66e3314921552d9330a4b05b18800'
# 13 digit channel id startswith - like -111.......
dump_id: '-1002399310545'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOHkBu07eSZAM-ukGmojV33Iaq0kKud5BVTsrojfrFzgSKMvhZhRGdopjBHWm8hssJqCnC3K925FX_6aQB8iCCCduuzARPHOwYJ7CP-0KYN2jmynduooU5ntFEA9H6wc1XhXev2u8mXYDsiBvGv-hPFOFr4QgnJV2qVtRDqUMQM_ea9QMIxlcd0Xlo1SJwDUWvFUDIq1zzu4x5qbi262HLm0LUsdFZ6_oogrXb90gZIaM29iPCq6H-b-N46xb5Uwf1CcJszCh2fF_kCXoi_iUTHg6WVIwrnO9454tJJCHPsw7Mqz5bhdHpZbUadK3L_VBbZCD_0PQX24bFakmnPD__GZMznQ='
